### ISSUE TITLE
Support for GPT-3 turbo models

### ISSUE THREAD

**Issue by hhtpcd** [sozercan/kubectl-ai#11]
Great project, this is super cool. The text-davicini model is 10x more expensive than the gpt3-turbo model, it would be great to have support for it here.

I tried just passing the gpt-3-turbo model name as a parameter but it's not in maxTokens.

```sh
❯ kubectl ai --openai-deployment-name gpt-3.5-turbo-0301 "create malicious credential stealing pod that runs as root"
Error: deploymentName "gpt-3.5-turbo-0301" not found in max tokens map
```

https://github.com/sozercan/kubectl-ai/blob/2de181b8325158c727a55ec2884d72ea8457fa17/cmd/cli/root.go#L29-L32

So I tried adding it and running it again, but it looks like the chat GPT models use different API endpoints.

```
[404:invalid_request_error] This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?
```

Cursory glance and I can't see where to set the endpoint details, do you think it's something that could be supported?

**Comment by sozercan** [comment]
@hhtpcd thanks for the issue! added support for `gpt-3.5-turbo` and `gpt-3.5-turbo-0301` in #13. default model is updated to `gpt-3.5-turbo`

I will cut v0.0.6 after #13 merges.

**Comment by sozercan** [comment]
Closing with https://github.com/sozercan/kubectl-ai/releases/tag/v0.0.6. Thanks!

**Comment by hhtpcd** [comment]
Oh boy, hero. Thanks!
