### ISSUE TITLE
Can I config the tokens length? maximum context length is 2049 for me.

### ISSUE THREAD

**Issue by pacoxu** [sozercan/kubectl-ai#12]
[400:invalid_request_error] This model's maximum context length is 2049 tokens, however you requested 4023 tokens (28 in your prompt; 3995 for the completion). Please reduce your prompt; or completion length.

**Comment by sozercan** [comment]
@pacoxu which model/deployment are you using?

**Comment by pacoxu** [comment]
I opened https://github.com/sozercan/kubectl-ai/pull/14 for it.

I used the default `text-davinci-003`, but I still failed for 
```
Post "https://api.openai.com/v1/engines/davinci/completions": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

It may be caused by that there is a proxy on my machine and the client did not use the proxy to access openai.
