### ISSUE TITLE
Error: [429:insufficient_quota] You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by audrastump** [sozercan/kubectl-ai#58]
I keep getting this error even though I still have $18.00 of credit in my OpenAI account. I am using a free trial of OpenAI and this was the first request I made using this account so I don't think I should have exceeded this quota.

**Comment by eyal-solomon1** [comment]
can it be you are not using the correct API key ? check whats exported for `OPENAI_API_KEY`

**Comment by sozercan** [comment]
This error is coming from OpenAI service. Closing this for now, feel free to re-open if you have more information.
